import * as hugeicons from '@hugeicons/core-free-icons';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Official Stroke Rounded geometry. Deliberately ship only the showcase's semantic subset.
const mapping = {
  Home: 'Home01', Components: 'GridView', Playground: 'Code', Foundation: 'Layers01',
  Settings: 'Settings01', Back: 'ArrowLeft01', Forward: 'ArrowRight01', Copy: 'Copy01',
  Check: 'Tick02', Close: 'Cancel01', Search: 'Search01', Dark: 'Moon02', Light: 'Sun03',
  Reset: 'Refresh', Code: 'Code', Play: 'Play', Info: 'InformationCircle',
  Expand: 'ArrowDown01', Collapse: 'ArrowUp01', Phone: 'SmartPhone01', Tablet: 'Tablet01',
  System: 'Computer', Documentation: 'BookOpen01', Palette: 'Palette', Sliders: 'SlidersHorizontal', Accessibility: 'Accessibility',
};
const root = fileURLToPath(new URL('../../', import.meta.url));
let output = `// Generated by tools/icons/generate.mjs from @hugeicons/core-free-icons 4.3.0.
// Copyright Hugeicons. MIT license: app/src/main/assets/licenses/hugeicons.txt.
package io.github.codewitheswar.frogui.showcase.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

/** The sole showcase icon boundary. Vendor data never enters a FrogUI library API. */
internal object FrogIcons {
`;
for (const [semantic, upstream] of Object.entries(mapping)) {
  const icon = hugeicons[`${upstream}Icon`];
  if (!icon) throw new Error(`Missing official icon ${upstream}`);
  output += `    // Hugeicons ${upstream}Icon, Stroke Rounded.\n    val ${semantic}: ImageVector by lazy {\n        ImageVector.Builder(name = "${semantic}", defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f, autoMirror = ${['Back', 'Forward'].includes(semantic)}).apply {\n`;
  for (const [type, attrs] of icon) {
    let d = attrs.d;
    if (type === 'circle') {
      const [x, y, r] = [attrs.cx, attrs.cy, attrs.r].map(Number);
      d = `M${x-r},${y}a${r},${r} 0 1,0 ${2*r},0a${r},${r} 0 1,0 ${-2*r},0`;
    } else if (type !== 'path') throw new Error(`Unsupported geometry ${type}`);
    if (attrs.fill && attrs.fill !== 'none') throw new Error('Review fill before generating');
    output += `            addPath(pathData = PathParser().parsePathString(${JSON.stringify(d)}).toNodes(), fill = null, stroke = SolidColor(Color.Black), strokeLineWidth = ${Number(attrs.strokeWidth ?? 1.5)}f, strokeLineCap = StrokeCap.${attrs.strokeLinecap === 'round' ? 'Round' : 'Butt'}, strokeLineJoin = StrokeJoin.${attrs.strokeLinejoin === 'round' ? 'Round' : 'Miter'})\n`;
  }
  output += `        }.build()\n    }\n`;
}
output += '}\n';
const destination = root + 'app/src/main/java/io/github/codewitheswar/frogui/showcase/icons/FrogIcons.kt';
if (process.argv.includes('--check')) {
  if (readFileSync(destination, 'utf8') !== output) throw new Error('FrogIcons is stale; run node tools/icons/generate.mjs');
} else {
  mkdirSync(root + 'app/src/main/java/io/github/codewitheswar/frogui/showcase/icons', { recursive: true });
  writeFileSync(destination, output);
}
console.log(`${Object.keys(mapping).length} semantic icons verified from the pinned Hugeicons package.`);
